spring:
  application:
    name: TECHMARKET-ia
  profiles:
    default: dev

server:
  port: 8082

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
